### ISSUE TITLE
Find Hardware Dependecies

### ISSUE THREAD

**Issue by ormaq** [499CSpeaking/SpeakingPortal#34]
What we need from cloud providers to make sure our code runs.

For example if we plan to use a nvidia product do we need to find a nvidia hardware cloud provider.

**Comment by jtyrmn** [comment]
Can we have Kukarella supply us all with RTX 3080s? for uhhh, researching audio2face

**Comment by jtyrmn** [comment]
We probably aren't going to use Audio2face though, it's designed for high-fidelity gaming and isn't designed for cloud computation.
