### ISSUE TITLE
Generate speaking portrait

### ISSUE THREAD

**Issue by ZuShi0** [499CSpeaking/SpeakingPortal#63]
Requirements:
- [x] #93
- [x] UI allows user to select from 4 (maybe?) avatars
- [x] #62 
- [x] #61 
- [x] Uses generated phonemes and animation assets to generate video (mp4?)

Closing Criteria:
- [ ] Requirements all completed
- [ ] Code review pass
- [ ] Unit/Automated test pass
- [ ] Post merge test pass

**Comment by ZuShi0** [comment]
We will be looking at this issue for the second term potentially

**Comment by jtyrmn** [comment]
We've made some good progress with this!

**Comment by ZuShi0** [comment]
Closing as we have passed this milestone
